// Auto-generated by tools/generate-keys.js
// This public key is embedded in the POS app to verify offline licenses.
// It CANNOT be used to forge licenses.

export const ZABAD_LICENSE_PUBLIC_KEY = "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEA2a0tANUIbMVQsT9ErQ41l068qJdekApvGiZOlquwR7M=\n-----END PUBLIC KEY-----";
