const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

const keysDir = path.resolve(__dirname, '../crypto-keys');
if (!fs.existsSync(keysDir)) {
  fs.mkdirSync(keysDir, { recursive: true });
}

const privateKeyPath = path.join(keysDir, 'private.key');
const publicKeyPath = path.join(keysDir, 'public.key');
const sharedTsPath = path.resolve(__dirname, '../src/shared/license-public-key.ts');

console.log('Generating Ed25519 Key Pair for Zabad Licensing...');

const { publicKey, privateKey } = crypto.generateKeyPairSync('ed25519');

const privateKeyPem = privateKey.export({ type: 'pkcs8', format: 'pem' });
const publicKeyPem = publicKey.export({ type: 'spki', format: 'pem' });

fs.writeFileSync(privateKeyPath, privateKeyPem, 'utf8');
fs.writeFileSync(publicKeyPath, publicKeyPem, 'utf8');

const tsContent = `// Auto-generated by tools/generate-keys.js
// This public key is embedded in the POS app to verify offline licenses.
// It CANNOT be used to forge licenses.

export const ZABAD_LICENSE_PUBLIC_KEY = ${JSON.stringify(publicKeyPem.trim())};
`;

fs.writeFileSync(sharedTsPath, tsContent, 'utf8');

console.log('SUCCESS: Key pair generated.');
console.log('Private key:', privateKeyPath);
console.log('Public key:', publicKeyPath);
console.log('Shared TS key:', sharedTsPath);
